---

    - name: A playbook to DL images and then UL to Openstack Glance
      hosts: localhost
      connection: local

      vars:
        img_to_dl: "https://cloud-images.ubuntu.com/focal/20200322/focal-server-cloudimg-amd64-disk-kvm.img"
        ansible_python_interpreter: "/usr/bin/python"

      tasks:
      #download image that will be uploaded to OpenStack Glance
      - name: Download the images "{{ img_to_dl }}"
        get_url:
          url: "{{ img_to_dl }}"
          dest: /home/centos/ans/

      - name: Upload the image "{{ img_to_dl }}"
        os_image:
          cloud: alta3cloud
          name: 20200322-focal-server-cloudimg-amd64-disk-kvm
          container_format: bare
          disk_format: qcow2
          state: present
          filename: /home/centos/ans/focal-server-cloudimg-amd64-disk-kvm.img
          properties:
            cpu_arch: x86_64
            distro: ubuntu

